### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by eaba** [IwraStudios/Whatsapp-Bot#2]
Hi @IwraStudios can you help?
I am trying to implement login, but dont seem to know how.
when Selenium navigates to web.whatsapp.com, if there are no cookies saved, I want to grab the QR image and display it for the user to scan, how can I implement this?

I cannot find `WebDriverEventListener` to implement `afterNavigateTo` to grab the requested page.

Thanks!

**Comment by IwraStudios** [comment]
I haven't implemented that part yet.
before [commit](https://github.com/IwraStudios/Whatsapp-Bot/commit/85b2c470e1fcd54583f847897ab55438e92c8e99) i had a project which just started the "default" bot, there were [lines](https://github.com/IwraStudios/Whatsapp-Bot/blob/ef31d9cd0272586a100423f4447ee6c1815c9f7a/WhatsappBot/Program.cs#L84) with `TODO: auto detect`
but after I made the API I forgot about it

I will once again try to implement it before tomorrow, also I will try to make the WebDriver somewhat public so people can do custom stuff.

Also about the QR you can download the image from source I'll include a snippet after I've implemented the things I talked about

EDIT: I've looked at the QR image and it is managed in raw instead of a reference, so you will have to construct your own bitmap

EDIT EDIT: I've made functions that get the QR Image/String (not on github yet) which you can use

**Comment by IwraStudios** [comment]
I've added most of the functions which you can see by the commit referenced above
I've also changed the *example program* to implement what you were talking about:
*Checking if it's logged in and saving/getting QR code*

**Comment by eaba** [comment]
Thanks. Appreciated

**Comment by eaba** [comment]
@IwraStudios  one more thing,
WhatsApp web lets you know when the phone is not connected, can this be achieved?
I need to use that to alert users when their phone is not online/disconnected.
Thanks
